### ISSUE TITLE
How to prevent entering next digit if the longest number is achieved?

### ISSUE THREAD

**Issue by ua9msn** [halt-hammerzeit/libphonenumber-js#34]
Hello! 
Could you please advise me how to prevent entering next digit if the longest number is achieved for the given country? 
I can not rely on the validation result, for small length, it returns false too. 
Maximum lengths for a country are different, so I can not just set it to 15.

**Comment by halt-hammerzeit** [comment]
Currently there's no such feature in this library.
Both iOS and Android don't restrict a user from entering any phone number because new phone numbers can emerge not covered by current regular expressions.
Google's `libphonenumber` doesn't have such a max length feature and this library doesn't too because it's a port the former.
