### ISSUE TITLE
Add findNumbers functionality from libphonenumber

### ISSUE THREAD

**Issue by netanelgilad** [halt-hammerzeit/libphonenumber-js#66]
Hi,
we are currently using this awesome port for parsing and formatting phone numbers.
Is there a plan to also implement the `findNumbers` functionality from `libphonenumber`? 

I can help with implementing if that's on the plan... 🍻

**Comment by halt-hammerzeit** [comment]
As far as I can see `findNumbers` is not part of the original `javascript` package which is understandable because crawlers and parsers are backend-driven and are therefore written in CPP and Java.
https://github.com/googlei18n/libphonenumber/search?utf8=%E2%9C%93&q=findNumbers&type=
Though I used to code Java a lot in the past, I don't write any crawlers so I don't need that `findNumbers` function, but if you do you can write it though I'm not sure right now if it's needed in this library.
Given that ES6 brings tree shaking it might not have any impact on other users, but I guess rather than depending on me to publish your code you would prefer instead publish your code in your own package so that you could be in control if you know what I mean.

**Comment by netanelgilad** [comment]
Makes a lot of sense @halt-hammerzeit. 
Are the any internal functions/regexes that this library could  expose for me to build a package based on this one?

**Comment by halt-hammerzeit** [comment]
If you happen to need any (in the final code) then leave a comment here and I'll export them.
Until you're ready to publish you can copy&paste them (i modified some of them a bit, btw).
Since you'll be migrating a Java version, I'd suppose you'd better stick with the original regexps since they're untouched.
